const demoStores = [
  ['Mobiles Store', 'mobiles-store', 'scale', '#1d4ed8'],
  ['Cloths Store', 'cloths-store', 'growth', '#be185d'],
  ['Slippers Store', 'slippers-store', 'starter', '#0f766e'],
  ['Electronics Store', 'electronics-store', 'scale', '#0f766e'],
  ['Shoes Store', 'shoes-store', 'growth', '#991b1b'],
  ['Grocery Store', 'grocery-store', 'growth', '#4d7c0f'],
  ['Kitchen Store', 'kitchen-store', 'growth', '#c16622'],
  ['Furniture Store', 'furniture-store', 'scale', '#7c3f00'],
  ['Beauty Store', 'beauty-store', 'growth', '#b83280'],
  ['Toys Store', 'toys-store', 'starter', '#7c5cc4'],
  ['Books Store', 'books-store', 'starter', '#4338ca'],
  ['Bags Store', 'bags-store', 'starter', '#7c5cc4']
];

const importedProductsByStore = {
  'mobiles-store': [
    ['Samsung Galaxy A36 5G Awesome White 8 GB RAM 128 GB', 'Premium 5G smartphone with 8 GB RAM, 128 GB storage, Super AMOLED display, and 5000 mAh battery.', 'Mobiles', 28330, 36, 'https://rukminim2.flixcart.com/image/480/640/xif0q/mobile/s/y/s/-original-imahghmrpjysyghq.jpeg?q=80'],
    ['iQOO Z10 Lite 5G Cyber Green 128 GB', 'Budget 5G smartphone with 128 GB storage, long battery life, and smooth everyday performance.', 'Mobiles', 18999, 41, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/n/n/l/z10-lite-5g-i2409-iqoo-original-imahjc5ebg6mhsvt.jpeg?q=90'],
    ['iQOO Z11x 5G Prismatic Green 128 GB', 'Battery focused 5G smartphone with large display, 50MP rear camera, and high-capacity battery.', 'Mobiles', 21399, 26, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/2/t/p/z11x-5g-i2507-iqoo-original-imahhph7grxwg24r.jpeg?q=90'],
    ['iQOO Z11x 5G Titan Black 128 GB', 'Performance 5G smartphone in Titan Black with 128 GB storage and fast daily multitasking.', 'Mobiles', 21899, 18, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/q/2/f/z11x-5g-i2507-iqoo-original-imahhzhhahgczhnx.jpeg?q=90'],
    ['Samsung Galaxy A35 5G Awesome Navy 128 GB', 'Mid-range Samsung 5G smartphone with vivid display, dependable camera, and all-day battery.', 'Mobiles', 24999, 24, 'https://rukminim2.flixcart.com/image/480/640/xif0q/mobile/s/y/s/-original-imahghmrpjysyghq.jpeg?q=80'],
    ['iQOO Z10 Lite 5G Titanium Black 128 GB', 'Value 5G smartphone with dark finish, reliable battery, and fast app performance.', 'Mobiles', 18499, 35, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/n/n/l/z10-lite-5g-i2409-iqoo-original-imahjc5ebg6mhsvt.jpeg?q=90'],
    ['iQOO Z11x 5G Prismatic Green 256 GB', 'Higher storage 5G smartphone with 256 GB capacity, large screen, and power-user battery life.', 'Mobiles', 23999, 17, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/2/t/p/z11x-5g-i2507-iqoo-original-imahhph7grxwg24r.jpeg?q=90'],
    ['iQOO Z11x 5G Titan Black 256 GB', 'Higher storage performance 5G smartphone with Titan Black finish and 256 GB capacity.', 'Mobiles', 24499, 16, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/q/2/f/z11x-5g-i2507-iqoo-original-imahhzhhahgczhnx.jpeg?q=90'],
    ['Samsung Galaxy A36 5G Awesome White 256 GB', 'Premium storage variant with Super AMOLED display, refined white finish, and 5G connectivity.', 'Mobiles', 31999, 19, 'https://rukminim2.flixcart.com/image/480/640/xif0q/mobile/s/y/s/-original-imahghmrpjysyghq.jpeg?q=80'],
    ['iQOO Z10 Lite 5G Cyber Green 256 GB', 'Affordable 5G smartphone with extra storage, bright green finish, and dependable battery backup.', 'Mobiles', 20999, 28, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/n/n/l/z10-lite-5g-i2409-iqoo-original-imahjc5ebg6mhsvt.jpeg?q=90'],
    ['iQOO Z11x 5G Prismatic Green 8 GB RAM 128 GB', '8 GB RAM smartphone variant for smoother gaming, multitasking, and daily 5G use.', 'Mobiles', 22999, 21, 'https://rukminim2.flixcart.com/image/300/300/xif0q/mobile/2/t/p/z11x-5g-i2507-iqoo-original-imahhph7grxwg24r.jpeg?q=90'],
    ['Samsung Galaxy A36 5G Awesome White 12 GB RAM 256 GB', 'Top memory variant with 12 GB RAM, 256 GB storage, Super AMOLED display, and premium finish.', 'Mobiles', 34999, 12, 'https://rukminim2.flixcart.com/image/480/640/xif0q/mobile/s/y/s/-original-imahghmrpjysyghq.jpeg?q=80']
  ],
  'cloths-store': [
    ['Men Classic White Formal Shirt', 'Men formal style shirt with crisp collar, office-ready fit, and clean white cotton finish.', 'Mens Clothing', 1299, 44, 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=900&q=80'],
    ['Men Navy Slim Fit Blazer', 'Men business and party style blazer with slim tailoring, navy finish, and structured shoulders.', 'Mens Clothing', 4999, 18, 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80'],
    ['Men Blue Denim Jacket', 'Men casual street style denim jacket with layered styling and everyday rugged finish.', 'Mens Clothing', 2499, 26, 'https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=900&q=80'],
    ['Men Cotton Printed T-Shirt', 'Men casual style printed t-shirt for daily wear, relaxed weekends, and light layering.', 'Mens Clothing', 699, 72, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'],
    ['Men Black Hoodie Sweatshirt', 'Men winter casual hoodie with soft fleece feel, kangaroo pocket, and streetwear style.', 'Mens Clothing', 1599, 39, 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80'],
    ['Men Beige Chino Trousers', 'Men smart casual chino trousers with tapered fit, neutral beige color, and office-to-weekend style.', 'Mens Clothing', 1399, 51, 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80'],
    ['Men Ethnic Kurta Set', 'Men festive ethnic kurta set with traditional styling, breathable fabric, and clean embroidered detail.', 'Mens Clothing', 2199, 28, 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80'],
    ['Men Activewear Track Suit', 'Men sports style track suit with flexible fit, breathable finish, and gym-ready comfort.', 'Mens Clothing', 1899, 35, 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80'],
    ['Men Party Wear Black Shirt', 'Men evening party style black shirt with sharp collar, smooth finish, and tailored look.', 'Mens Clothing', 1499, 31, 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?auto=format&fit=crop&w=900&q=80'],
    ['Men Winter Puffer Jacket', 'Men winterwear puffer jacket with warm padded body, travel styling, and cold-weather comfort.', 'Mens Clothing', 3499, 20, 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=900&q=80'],
    ['Women Floral Summer Dress', 'Women casual floral dress with light summer styling, flowy silhouette, and soft everyday comfort.', 'Womens Clothing', 1799, 46, 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80'],
    ['Women Black Party Gown', 'Women party style gown with elegant black finish, evening silhouette, and occasion-ready detail.', 'Womens Clothing', 3999, 16, 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80'],
    ['Women Formal Blazer Set', 'Women office style blazer set with tailored fit, modern professional styling, and polished finish.', 'Womens Clothing', 4599, 21, 'https://images.unsplash.com/photo-1549351512-c5e12b11e283?auto=format&fit=crop&w=900&q=80'],
    ['Women Denim Jacket', 'Women casual denim jacket with street style layering, relaxed fit, and versatile blue wash.', 'Womens Clothing', 2299, 33, 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80'],
    ['Women Ethnic Kurti Set', 'Women ethnic kurti set with festive styling, graceful drape, and comfortable daily-traditional wear.', 'Womens Clothing', 1999, 42, 'https://images.unsplash.com/photo-1587651134736-d5b7b590071c?auto=format&fit=crop&w=900&q=80'],
    ['Women Saree Designer Style', 'Women designer saree style with elegant drape, occasion-ready fabric, and traditional finish.', 'Womens Clothing', 2999, 24, 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80'],
    ['Women Sports Leggings', 'Women activewear leggings with stretch fit, workout comfort, and clean athletic styling.', 'Womens Clothing', 999, 65, 'https://images.unsplash.com/photo-1506629905607-d9c36e0a3c7c?auto=format&fit=crop&w=900&q=80'],
    ['Women Oversized Hoodie', 'Women casual oversized hoodie with cozy fleece styling, relaxed streetwear fit, and winter comfort.', 'Womens Clothing', 1699, 37, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=900&q=80'],
    ['Women Wide Leg Trousers', 'Women smart casual wide leg trousers with high waist style, soft drape, and modern office look.', 'Womens Clothing', 1599, 49, 'https://images.unsplash.com/photo-1551854838-212c50b4c184?auto=format&fit=crop&w=900&q=80'],
    ['Women Casual Crop Top', 'Women casual crop top with summer styling, soft knit feel, and easy pairing with denim or skirts.', 'Womens Clothing', 799, 70, 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80']
  ],
  'slippers-store': [
    ['Men Classic Rubber Flip Flops', 'Men everyday flip-flop slippers with flexible rubber sole, simple strap, and easy home-outdoor use.', 'Slippers', 399, 88, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/c/e/8/-original-imagz625pprcmghz.jpeg?q=70'],
    ['Men Cushioned Home Slippers', 'Men soft home slippers with padded footbed, indoor comfort, and relaxed daily wear styling.', 'Slippers', 699, 62, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/o/v/4/-original-imagz625tqgrzbsr.jpeg?q=70'],
    ['Men Sport Slide Slippers', 'Men sporty slide slippers with wide strap, cushioned sole, and gym-shower casual styling.', 'Slippers', 899, 54, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/q/t/i/-original-imagz625evyh6zbw.jpeg?q=70'],
    ['Men Leather Strap Slippers', 'Men premium casual slippers with leather-style strap, molded sole, and smart everyday look.', 'Slippers', 1199, 36, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/l/k/v/-original-imagz625hghcyf3d.jpeg?q=70'],
    ['Men Orthopedic Comfort Slippers', 'Men orthopedic slippers with arch support, soft heel cup, and long-wear comfort for daily use.', 'Slippers', 1499, 28, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/x/o/s/-original-imagz625whnqzgbb.jpeg?q=70'],
    ['Men Beach Flip Flop Slippers', 'Men beach style slippers with lightweight sole, water-friendly build, and vacation-ready color.', 'Slippers', 499, 76, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/e/o/v/-original-imagz625tghfwgef.jpeg?q=70'],
    ['Men Ethnic Kolhapuri Slippers', 'Men ethnic slipper style with traditional strap design, festive outfit pairing, and flat sole.', 'Slippers', 999, 40, 'https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/g/u/b/6-9311-6-world-wear-footwear-tan-original-imagzhffwhqktpgb.jpeg?q=70'],
    ['Men Winter Fur Slippers', 'Men cozy winter slippers with warm lining, soft upper, and indoor cold-weather comfort.', 'Slippers', 1299, 32, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/a/z/m/-original-imagz625zdpmcxgy.jpeg?q=70'],
    ['Women Soft Fur Home Slippers', 'Women soft fur slippers with plush footbed, cozy indoor styling, and relaxed home comfort.', 'Slippers', 799, 64, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/h/z/u/-original-imagz625edzeyrgy.jpeg?q=70'],
    ['Women Fashion Slide Slippers', 'Women fashion slide slippers with wide strap, modern casual look, and easy daily styling.', 'Slippers', 899, 58, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/s/k/e/-original-imagz625qw7rjhyp.jpeg?q=70'],
    ['Women Floral Flip Flop Slippers', 'Women floral flip-flop slippers with printed strap, lightweight sole, and summer casual styling.', 'Slippers', 449, 82, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/y/y/f/-original-imagz625yd7jc8vy.jpeg?q=70'],
    ['Women Wedge Heel Slippers', 'Women wedge slipper style with raised heel, festive casual look, and comfortable party wear fit.', 'Slippers', 1299, 34, 'https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/n/f/m/5-2095-5-denill-beige-original-imah37shygv9knfh.jpeg?q=70'],
    ['Women Orthopedic Cloud Slippers', 'Women orthopedic comfort slippers with soft cushioning, arch support, and daily walking ease.', 'Slippers', 1399, 29, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/w/z/v/-original-imagz625zhkdzfhf.jpeg?q=70'],
    ['Women Ethnic Embellished Slippers', 'Women ethnic embellished slippers with festive strap detail, flat sole, and traditional outfit styling.', 'Slippers', 1099, 38, 'https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/l/t/m/4-2068-4-denill-gold-original-imagzy2yuquphsqb.jpeg?q=70'],
    ['Women Bathroom Anti-Skid Slippers', 'Women bathroom slippers with anti-skid sole, water-friendly material, and quick-dry comfort.', 'Slippers', 349, 90, 'https://rukminim2.flixcart.com/image/612/612/xif0q/slipper-flip-flop/b/i/w/-original-imagz625qhtswfhe.jpeg?q=70'],
    ['Women Platform Slippers', 'Women platform slipper style with thick sole, casual height boost, and modern streetwear look.', 'Slippers', 1199, 42, 'https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/1/k/c/5-2066-5-denill-black-original-imagzy2ybbqzegsp.jpeg?q=70']
  ],
  'electronics-store': [
    ['Wireless Bluetooth Headphones', 'Audio electronics with over-ear comfort, wireless Bluetooth pairing, and long battery playback.', 'Electronics', 2499, 45, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80'],
    ['True Wireless Earbuds', 'Compact audio earbuds with charging case, touch controls, and everyday music-call convenience.', 'Electronics', 1799, 60, 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80'],
    ['JBL Cinema 2.1 Bluetooth Soundbar', 'Home audio soundbar with subwoofer style setup, Bluetooth support, and TV entertainment sound.', 'Electronics', 7999, 31, 'https://rukminim2.flixcart.com/image/480/640/xif0q/speaker/p/b/d/-original-imahcjzzpcrw5z5h.jpeg?q=80'],
    ['Portable Bluetooth Speaker', 'Portable speaker electronics with compact body, wireless audio, and outdoor-friendly sound.', 'Electronics', 1499, 54, 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80'],
    ['Transparent Wireless Mouse Red', 'Computer accessory mouse with Bluetooth, 2.4 GHz support, rechargeable battery, and silent click design.', 'Electronics', 599, 86, 'https://rukminim2.flixcart.com/image/480/640/xif0q/mouse/a/v/9/toad-8-transparent-wireless-mouse-bluetooth-2-4ghz-rechargeable-original-imahd9bw4v6ewdfy.jpeg?q=80'],
    ['Mechanical Gaming Keyboard RGB', 'Gaming electronics keyboard with mechanical switches, RGB lighting, and fast desktop control.', 'Electronics', 3499, 28, 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?auto=format&fit=crop&w=900&q=80'],
    ['Laptop 15 Inch Work Edition', 'Work laptop with portable design, productivity performance, and everyday office-study capability.', 'Electronics', 54999, 15, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80'],
    ['Tablet 10 Inch Wi-Fi', 'Tablet electronics with large touch display, Wi-Fi support, and entertainment-study use.', 'Electronics', 18999, 24, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80'],
    ['Smart Watch Fitness Edition', 'Wearable electronics watch with fitness tracking, notifications, and health-style daily monitoring.', 'Electronics', 2999, 52, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80'],
    ['Smart LED TV 43 Inch', 'Home entertainment electronics with smart streaming, large LED display, and living room viewing.', 'Electronics', 28999, 18, 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=900&q=80'],
    ['DSLR Camera Creator Kit', 'Camera electronics kit for photography, video creation, portraits, and travel shoots.', 'Electronics', 45999, 12, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80'],
    ['Action Camera 4K Waterproof', 'Adventure camera electronics with 4K recording, compact body, and waterproof outdoor use.', 'Electronics', 8999, 20, 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=80'],
    ['Power Bank 20000 mAh Fast Charge', 'Charging electronics power bank with high capacity, fast charging, and travel backup power.', 'Electronics', 1699, 70, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=900&q=80'],
    ['USB-C Fast Charger 65 W', 'Mobile and laptop charger with USB-C fast charging, compact adapter design, and daily power use.', 'Electronics', 1299, 76, 'https://images.unsplash.com/photo-1585079542156-2755d9c8affd?auto=format&fit=crop&w=900&q=80'],
    ['External SSD 1 TB', 'Storage electronics SSD with portable body, fast file transfer, and creator backup use.', 'Electronics', 6999, 33, 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=900&q=80'],
    ['Wi-Fi Router Dual Band', 'Networking electronics router with dual band coverage, home internet support, and stable streaming.', 'Electronics', 2499, 42, 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?auto=format&fit=crop&w=900&q=80'],
    ['Smart Home Security Camera', 'Home security electronics camera with app monitoring, night vision style support, and compact mount.', 'Electronics', 2799, 39, 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?auto=format&fit=crop&w=900&q=80'],
    ['Robot Vacuum Cleaner', 'Home appliance electronics with automatic floor cleaning, smart navigation, and compact charging dock.', 'Electronics', 18999, 11, 'https://images.unsplash.com/photo-1603618090561-412154b4bd1b?auto=format&fit=crop&w=900&q=80'],
    ['Air Fryer Digital 5 L', 'Kitchen electronics appliance with digital control, oil-light cooking, and family-size basket.', 'Electronics', 5999, 25, 'https://images.unsplash.com/photo-1626084082767-336f57c2651a?auto=format&fit=crop&w=900&q=80'],
    ['Electric Kettle Stainless Steel', 'Kitchen electronics kettle with fast boiling, stainless steel body, and compact countertop design.', 'Electronics', 1199, 64, 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=80'],
    ['Gaming Controller Wireless', 'Gaming electronics controller with wireless play, ergonomic grip, and console-PC style controls.', 'Electronics', 2499, 37, 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=900&q=80'],
    ['VR Headset Immersive Edition', 'Entertainment electronics VR headset with immersive viewing, adjustable strap, and gaming-media use.', 'Electronics', 12999, 10, 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=900&q=80'],
    ['Desk LED Study Lamp', 'Lighting electronics lamp with adjustable neck, LED brightness, and study-work desk styling.', 'Electronics', 899, 55, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80'],
    ['Digital Alarm Clock Speaker', 'Home electronics clock with digital display, speaker style body, and bedside utility.', 'Electronics', 1499, 44, 'https://images.unsplash.com/photo-1501139083538-0139583c060f?auto=format&fit=crop&w=900&q=80']
  ],
  'flipkart-fashion-store': [
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers', 'Flipkart imported YGDEAL straight fit linen blend casual trousers listing.', 'Apparel', 740, 58, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/a/h/n/28-linen-700-yg-ygdeal-original-imahmuwthkym9qht.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Front View', 'Flipkart imported YGDEAL linen blend trouser gallery image.', 'Apparel', 740, 52, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/z/a/q/28-linen-700-yg-ygdeal-original-imahmuwtaanhrmyh.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Size 30', 'Flipkart imported YGDEAL linen blend trouser listing size variant.', 'Apparel', 740, 47, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/a/h/n/30-linen-700-yg-ygdeal-original-imahmuwthkym9qht.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Size 32', 'Flipkart imported YGDEAL linen blend trouser listing size variant.', 'Apparel', 740, 43, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/z/a/q/30-linen-700-yg-ygdeal-original-imahmuwtaanhrmyh.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Size 34', 'Flipkart imported YGDEAL linen blend trouser listing size variant.', 'Apparel', 740, 39, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/a/h/n/32-linen-700-yg-ygdeal-original-imahmuwthkym9qht.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Size 36', 'Flipkart imported YGDEAL dark green linen blend trouser size variant matched to trouser image.', 'Apparel', 740, 29, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/a/h/n/28-linen-700-yg-ygdeal-original-imahmuwthkym9qht.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Alternate View 1', 'Flipkart imported YGDEAL trouser gallery image matched to the same listing.', 'Apparel', 740, 33, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/z/a/q/28-linen-700-yg-ygdeal-original-imahmuwtaanhrmyh.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Alternate View 2', 'Flipkart imported YGDEAL trouser gallery image matched to the same listing.', 'Apparel', 740, 21, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/a/h/n/30-linen-700-yg-ygdeal-original-imahmuwthkym9qht.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Alternate View 3', 'Flipkart imported YGDEAL trouser gallery image matched to the same listing.', 'Apparel', 740, 48, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/z/a/q/30-linen-700-yg-ygdeal-original-imahmuwtaanhrmyh.jpeg?q=80'],
    ['YGDEAL Men Straight Fit Dark Green Linen Blend Trousers Alternate View 4', 'Flipkart imported YGDEAL trouser gallery image matched to the same listing.', 'Apparel', 740, 37, 'https://rukminim2.flixcart.com/image/480/640/xif0q/trouser/a/h/n/32-linen-700-yg-ygdeal-original-imahmuwthkym9qht.jpeg?q=80']
  ],
  'shoes-store': [
    ['Men Running Shoes Lightweight Mesh', 'Athletic running style shoes with breathable mesh, cushioned sole, and daily workout comfort.', 'Shoes', 2199, 48, 'https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/k/h/-resized-2-original-imahg3b6gmb9xbma.jpeg?q=70'],
    ['Men White Court Sneakers', 'Casual sneaker style shoes with clean white finish, low-top profile, and everyday streetwear look.', 'Shoes', 1999, 52, 'https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/i/t/10-l100073-10-0-lotto-red-white-original-imahfv3br8zur69g.jpeg?q=70'],
    ['Men Black Formal Oxford Shoes', 'Formal office style Oxford shoes with polished black finish, lace-up build, and sharp trouser pairing.', 'Shoes', 2999, 29, 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=900&q=80'],
    ['Men Brown Leather Loafers', 'Smart casual loafer style shoes with brown leather finish, slip-on comfort, and semi-formal styling.', 'Shoes', 2499, 34, 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=900&q=80'],
    ['Men Trekking Boots Outdoor Grip', 'Outdoor trekking style boots with ankle support, rugged sole grip, and trail-ready build.', 'Shoes', 3499, 22, 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=900&q=80'],
    ['Men Slip-On Walking Shoes', 'Comfort walking style slip-on shoes with flexible sole, padded collar, and easy daily wear.', 'Shoes', 2587, 40, 'https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/3/t/r/12-l100084-12-lotto-black-grey-original-imahm35nh5x4ggsh.jpeg?q=70'],
    ['Men Basketball High Top Shoes', 'Sports basketball style shoes with high-top ankle support, court grip, and bold street look.', 'Shoes', 3999, 18, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'],
    ['Men Canvas Casual Shoes', 'Classic canvas style shoes with lace-up design, lightweight comfort, and relaxed weekend styling.', 'Shoes', 999, 67, 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80'],
    ['Women Fashion Sneakers Pastel', 'Women casual fashion sneaker style with pastel color, soft sole, and everyday denim-friendly look.', 'Shoes', 1899, 45, 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80'],
    ['Women Black Heeled Pumps', 'Women formal heel style pumps with pointed toe, elegant black finish, and party-office versatility.', 'Shoes', 2299, 27, 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80'],
    ['Women Ankle Boots Tan', 'Women ankle boot style shoes with tan finish, side profile, and casual winter outfit styling.', 'Shoes', 2999, 24, 'https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?auto=format&fit=crop&w=900&q=80'],
    ['Women Ballet Flats', 'Women flat shoe style with soft footbed, rounded toe, and comfortable daily office wear.', 'Shoes', 1299, 58, 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=900&q=80'],
    ['Women Sports Training Shoes', 'Women gym training style shoes with stable sole, breathable upper, and active workout comfort.', 'Shoes', 2499, 36, 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=900&q=80'],
    ['Women Block Heel Sandals', 'Women sandal style footwear with block heel, open toe, and festive casual styling.', 'Shoes', 1599, 41, 'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80'],
    ['Kids School Shoes Black', 'Kids school style shoes with durable black finish, easy cleaning, and comfortable classroom fit.', 'Shoes', 899, 80, 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=900&q=80'],
    ['Kids Colorful Sneakers', 'Kids playful sneaker style with bright colors, cushioned sole, and active day comfort.', 'Shoes', 1199, 63, 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=900&q=80'],
    ['Unisex Flip Flop Sandals', 'Easy casual sandal style footwear for beach, home, and quick everyday use.', 'Shoes', 399, 95, 'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80'],
    ['Unisex Rain Shoes Waterproof', 'Waterproof rain style shoes with easy-clean upper, anti-slip sole, and monsoon-ready comfort.', 'Shoes', 999, 56, 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=900&q=80'],
    ['Unisex Chunky Dad Sneakers', 'Chunky sneaker style shoes with bold sole, retro profile, and streetwear outfit pairing.', 'Shoes', 2799, 32, 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=900&q=80'],
    ['Unisex Minimal Slip-On Sneakers', 'Minimal slip-on sneaker style with clean upper, flexible sole, and effortless everyday styling.', 'Shoes', 1499, 50, 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=900&q=80']
  ],
  'grocery-store': [
    ['Sugar.fit Sugar Control Low GI Brown Rice 1 kg', 'Flipkart imported Sugar.fit brown sona masoori rice listing with high fiber and low GI positioning.', 'Grocery', 199, 92, 'https://rukminim2.flixcart.com/image/160/210/xif0q/rice/x/r/7/1-sugar-control-low-gi-brown-rice-high-fiber-gluten-free-original-imahgtbgdpdpzeme.jpeg?q=80'],
    ['Sugar.fit Sugar Control Brown Sona Masoori Rice Pack', 'Flipkart imported Sugar.fit brown rice gallery image.', 'Grocery', 199, 88, 'https://rukminim2.flixcart.com/image/160/210/xif0q/rice/i/w/3/1-sugar-control-low-gi-brown-rice-high-fiber-gluten-free-original-imahgtbg4sxwjted.jpeg?q=90'],
    ['FORTUNE SONA MASOORI REGULAR RICE 5 kg', 'Flipkart imported Fortune Sona Masoori regular rice listing.', 'Grocery', 450, 60, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/rice/b/r/z/5-sona-masoori-regular-rice-white-na-pouch-sona-masoori-rice-original-imagmychyky4pbjg.jpeg?q=80'],
    ['FORTUNE SONA MASOORI REGULAR RICE 5 kg Pouch View', 'Flipkart imported Fortune rice gallery image.', 'Grocery', 450, 54, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/rice/4/y/2/5-sona-masoori-regular-rice-white-na-pouch-sona-masoori-rice-original-imagmychbhf4jjga.jpeg?q=80'],
    ['FORTUNE SONA MASOORI REGULAR RICE 5 kg Pack Back View', 'Flipkart imported Fortune rice gallery image.', 'Grocery', 450, 48, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/rice/p/m/o/5-sona-masoori-regular-rice-white-na-pouch-sona-masoori-rice-original-imagmychjwgtjtme.jpeg?q=80'],
    ['Kelloggs Fruit Nut and Seeds 12-in-1 Muesli Cereal Pouch', 'Flipkart imported Kelloggs muesli cereal pouch listing.', 'Grocery', 376, 73, 'https://rukminim2.flixcart.com/image/300/300/xif0q/cereal-flake/v/c/j/-original-imagvscyatk9pcck.jpeg?q=90'],
    ['Kelloggs Fruit Nut and Seeds Muesli Pack View', 'Flipkart imported Kelloggs muesli gallery image.', 'Grocery', 376, 64, 'https://rukminim2.flixcart.com/image/704/844/xif0q/cereal-flake/2/6/o/-original-imagvscymkrzdxgc.jpeg?q=90'],
    ['Steel Cut Rolled Oats Jar and Pouch Combo', 'Flipkart imported oats combo listing.', 'Grocery', 399, 55, 'https://rukminim2.flixcart.com/image/480/640/xif0q/cereal-flake/5/9/c/1-4-1kg-x-1-jar-and-0-4kg-x-1-pouch-steel-cut-rolled-oats-original-imahg8dmhbasbzjg.jpeg?q=90'],
    ['Steel Cut Rolled Oats Combo Pack View', 'Flipkart imported oats combo gallery image.', 'Grocery', 399, 42, 'https://rukminim2.flixcart.com/image/480/640/xif0q/cereal-flake/h/m/w/1-4-1kg-x-1-jar-and-0-4kg-x-1-pouch-steel-cut-rolled-oats-original-imahg8dmrfrhdpgf.jpeg?q=90'],
    ['Sugar.fit Brown Sona Masoori Rice 1 kg Detail View', 'Flipkart imported Sugar.fit brown rice alternate image.', 'Grocery', 199, 80, 'https://rukminim2.flixcart.com/image/416/416/xif0q/rice/x/r/7/1-sugar-control-low-gi-brown-rice-high-fiber-gluten-free-original-imahgtbgdpdpzeme.jpeg?q=80']
  ],
  'kitchen-store': [
    ['Pigeon 1800 W Induction Cooktop Push Button with Kadai', 'Flipkart imported Pigeon induction cooktop listing with stainless steel induction base kadai.', 'Kitchen', 4281, 28, 'https://rukminim2.flixcart.com/image/612/612/xif0q/induction-cook-top/x/b/n/with-steelo-multipurpose-stainless-steel-induction-base-kadai-original-imahhxcsg3ftaqp5.jpeg?q=70'],
    ['Pigeon 1800 W Induction Cooktop Push Button ICT PRIME', 'Flipkart imported Pigeon ICT PRIME induction cooktop listing.', 'Kitchen', 2849, 37, 'https://rukminim2.flixcart.com/image/612/612/xif0q/induction-cook-top/x/x/d/prime-ict-1800-w-ict-prime-pigeon-original-imahjt9czz6sawej.jpeg?q=70'],
    ['Pigeon 1800 W Induction Cooktop Push Button Black', 'Flipkart imported Pigeon induction cooktop listing in black finish.', 'Kitchen', 2059, 56, 'https://rukminim2.flixcart.com/image/612/612/kyj0vbk0/induction-cook-top/z/i/x/-original-imagaqsnfxjxgug4.jpeg?q=70'],
    ['Pigeon Acer Plus Induction Cooktop with IB 3 Ltr Pressure Cooker Combo', 'Flipkart imported Pigeon Acer Plus induction cooktop and pressure cooker combo.', 'Kitchen', 2874, 25, 'https://rukminim2.flixcart.com/image/612/612/xif0q/induction-cook-top/x/b/n/with-steelo-multipurpose-stainless-steel-induction-base-kadai-original-imahhxcsg3ftaqp5.jpeg?q=70'],
    ['Mccoy 1800 W Induction Cooktop Push Button Rapido DX', 'Flipkart imported Mccoy induction cooktop listing.', 'Kitchen', 2499, 34, 'https://rukminim2.flixcart.com/image/612/612/xif0q/induction-cook-top/x/x/d/prime-ict-1800-w-ict-prime-pigeon-original-imahjt9czz6sawej.jpeg?q=70'],
    ['KEMAJUAN 1600 W Induction Cooktop Push Button', 'Flipkart imported KEMAJUAN induction cooktop listing.', 'Kitchen', 2784, 30, 'https://rukminim2.flixcart.com/image/612/612/kyj0vbk0/induction-cook-top/z/i/x/-original-imagaqsnfxjxgug4.jpeg?q=70'],
    ['Greenchef 2000 W Induction Cooktop Touch Panel', 'Flipkart imported Greenchef induction cooktop listing.', 'Kitchen', 2499, 27, 'https://rukminim2.flixcart.com/image/416/416/xif0q/induction-cook-top/x/b/n/with-steelo-multipurpose-stainless-steel-induction-base-kadai-original-imahhxcsg3ftaqp5.jpeg?q=70'],
    ['iBELL 2000 W Induction Cooktop Push Button', 'Flipkart imported iBELL induction cooktop listing.', 'Kitchen', 3598, 21, 'https://rukminim2.flixcart.com/image/612/612/xif0q/induction-cook-top/x/x/d/prime-ict-1800-w-ict-prime-pigeon-original-imahjt9czz6sawej.jpeg?q=70'],
    ['Tower 2000 W Induction Cooktop Push Button', 'Flipkart imported Tower induction cooktop listing.', 'Kitchen', 2849, 19, 'https://rukminim2.flixcart.com/image/612/612/kyj0vbk0/induction-cook-top/z/i/x/-original-imagaqsnfxjxgug4.jpeg?q=70'],
    ['PHILIPS by Philips 2100 W Induction Cooktop Touch Panel', 'Flipkart imported Philips induction cooktop listing.', 'Kitchen', 4999, 15, 'https://rukminim2.flixcart.com/image/416/416/xif0q/induction-cook-top/x/b/n/with-steelo-multipurpose-stainless-steel-induction-base-kadai-original-imahhxcsg3ftaqp5.jpeg?q=70']
  ],
  'furniture-store': [
    ['SleepyHug FoldPRO Sofa-Cum-Bed 3 Seater Double Foam Blue', 'Flipkart imported SleepyHug FoldPRO sofa-cum-bed listing.', 'Furniture', 9399, 18, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/4/m/l/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwzmcfay8y.jpeg?q=80'],
    ['SleepyHug FoldPRO Sofa-Cum-Bed 3 Seater Side View', 'Flipkart imported SleepyHug FoldPRO sofa-cum-bed gallery image.', 'Furniture', 9399, 16, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/z/v/u/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwwdzzt4cz.jpeg?q=90'],
    ['SleepyHug FoldPRO Sofa-Cum-Bed 3 Seater Bed View', 'Flipkart imported SleepyHug FoldPRO sofa-cum-bed converted bed view.', 'Furniture', 9399, 14, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/f/s/q/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwttgerfhk.jpeg?q=90'],
    ['SleepyHug FoldPRO Sofa-Cum-Bed 3 Seater Fold View', 'Flipkart imported SleepyHug FoldPRO sofa-cum-bed fold-out view.', 'Furniture', 9399, 12, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/a/5/3/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwhnkdzbyz.jpeg?q=90'],
    ['SleepyHug FoldPRO Sofa-Cum-Bed 3 Seater Detail View', 'Flipkart imported SleepyHug FoldPRO sofa-cum-bed detail view.', 'Furniture', 9399, 11, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/m/e/p/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjw4njwezqx.jpeg?q=90'],
    ['Solis Primus Comfort Sofa Cum Bed 3 Seater', 'Flipkart imported sofa-cum-bed category listing product.', 'Furniture', 8061, 20, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/4/m/l/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwzmcfay8y.jpeg?q=80'],
    ['Friends Fit Life Sofa Cum Bed 3 Seater', 'Flipkart imported sofa-cum-bed category listing product.', 'Furniture', 8122, 19, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/z/v/u/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwwdzzt4cz.jpeg?q=90'],
    ['Little Smile Sofa Cum Bed 1 Seater', 'Flipkart imported sofa-cum-bed category listing product.', 'Furniture', 5253, 24, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/f/s/q/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwttgerfhk.jpeg?q=90'],
    ['Roliwal Sheesham Wooden Sofa Cum Bed 2 Seater', 'Flipkart imported sofa-cum-bed category listing product.', 'Furniture', 24749, 8, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/a/5/3/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjwhnkdzbyz.jpeg?q=90'],
    ['Friends super Life Sofa Bed 3 Seater Double Foam', 'Flipkart imported sofa-cum-bed category listing product.', 'Furniture', 9001, 13, 'https://rukminim2.flixcart.com/image/480/640/xif0q/sofa-bed/m/e/p/double-19-3-seater-teal-cotton-152-no-24-ts-scb-3-t-sleepyhug-original-imahgzjw4njwezqx.jpeg?q=90']
  ],
  'beauty-store': [
    ['Molecular Structure Sunscreen SPF 50 PA++++ Blue Light Protection 50 g', 'Flipkart imported sunscreen listing with SPF 50 PA++++, blue light protection, and no white cast claim.', 'Beauty', 150, 65, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/sunscreen/c/1/4/50-blue-light-protection-lightweight-no-white-cast-best-quality-original-imahfwyrvmhx8qds.jpeg?q=80'],
    ['MARS Matte Muse Mousse Lipstick SHOW STOPPER 3 ml', 'Flipkart imported MARS Matte Muse Mousse Lipstick listing.', 'Beauty', 269, 74, 'https://rukminim2.flixcart.com/image/300/300/xif0q/lipstick/4/l/h/3-matte-muse-mousse-lipstick-mars-original-imah9kxhmj8gnwvq.jpeg?q=90'],
    ['MARS Matte Muse Mousse Lipstick Fashion Insta 3 ml', 'Flipkart imported MARS Matte Muse Mousse Lipstick gallery image.', 'Beauty', 269, 69, 'https://rukminim2.flixcart.com/image/480/640/xif0q/lipstick/f/d/q/3-matte-muse-mousse-lipstick-mars-original-imah7vx4rvcxjxhg.jpeg?q=90'],
    ['MARS Matte Muse Mousse Lipstick Swatch View 3 ml', 'Flipkart imported MARS lipstick shade gallery image.', 'Beauty', 269, 58, 'https://rukminim2.flixcart.com/image/480/640/xif0q/lipstick/g/h/n/3-matte-muse-mousse-lipstick-mars-original-imah9kxhav2dw6zm.jpeg?q=90'],
    ['MARS Matte Muse Mousse Lipstick Product View 3 ml', 'Flipkart imported MARS lipstick product image.', 'Beauty', 269, 52, 'https://rukminim2.flixcart.com/image/480/640/xif0q/lipstick/6/e/t/3-matte-muse-mousse-lipstick-mars-original-imah7vx4ecnyzvr6.jpeg?q=90'],
    ['Molecular Structure Sunscreen SPF 50 Product View', 'Flipkart imported Molecular Structure sunscreen product image matched to the same listing.', 'Beauty', 150, 40, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/sunscreen/c/1/4/50-blue-light-protection-lightweight-no-white-cast-best-quality-original-imahfwyrvmhx8qds.jpeg?q=80'],
    ['MARS Matte Muse Mousse Lipstick Product Image', 'Flipkart imported MARS Matte Muse Mousse Lipstick image matched to the same listing.', 'Beauty', 269, 31, 'https://rukminim2.flixcart.com/image/300/300/xif0q/lipstick/4/l/h/3-matte-muse-mousse-lipstick-mars-original-imah9kxhmj8gnwvq.jpeg?q=90'],
    ['MARS Matte Muse Mousse Lipstick Combo View', 'Flipkart imported MARS lipstick alternate product image.', 'Beauty', 269, 45, 'https://rukminim2.flixcart.com/image/480/640/xif0q/lipstick/f/d/q/3-matte-muse-mousse-lipstick-mars-original-imah7vx4rvcxjxhg.jpeg?q=90'],
    ['Molecular Structure Sunscreen SPF 50 Pack of 2', 'Flipkart imported Molecular Structure sunscreen pack listing.', 'Beauty', 150, 62, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/sunscreen/c/1/4/50-blue-light-protection-lightweight-no-white-cast-best-quality-original-imahfwyrvmhx8qds.jpeg?q=80'],
    ['MARS Matte Muse Mousse Lipstick Shade Detail', 'Flipkart imported MARS lipstick shade detail image.', 'Beauty', 269, 50, 'https://rukminim2.flixcart.com/image/480/640/xif0q/lipstick/g/h/n/3-matte-muse-mousse-lipstick-mars-original-imah9kxhav2dw6zm.jpeg?q=90']
  ],
  'toys-store': [
    ['COMERCIO Remote Control Stunt Vehicle 360 Rotating Rolling Racing Car Blue', 'Flipkart imported COMERCIO remote control stunt vehicle listing.', 'Toys', 277, 84, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/remote-control-toy/r/6/m/remote-control-stunt-vehicle-360-rotating-rolling-radio-electric-original-imahhsxfqexkzfky.jpeg?q=80'],
    ['COMERCIO Remote Control Stunt Vehicle Blue Side View', 'Flipkart imported COMERCIO stunt vehicle alternate product image.', 'Toys', 277, 76, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/remote-control-toy/q/k/s/remote-control-stunt-vehicle-360-rotating-rolling-radio-electric-original-imahhsxfaeavhz8z.jpeg?q=80'],
    ['DWH RC Drift Car for Adults High Speed 4X4 Remote Control Car', 'Flipkart imported DWH RC Drift Car listing.', 'Toys', 999, 42, 'https://rukminim2.flixcart.com/image/480/640/xif0q/remote-control-toy/x/t/6/rc-drift-car-for-adults-high-speed-4x4-remote-control-car-for-original-imahhfyzjsyz2mzh.jpeg?q=90'],
    ['DWH RC Drift Car 4X4 Remote Control Car Wheel View', 'Flipkart imported DWH RC Drift Car alternate product image.', 'Toys', 999, 38, 'https://rukminim2.flixcart.com/image/480/640/xif0q/remote-control-toy/5/m/h/rc-drift-car-for-adults-high-speed-4x4-remote-control-car-for-original-imahhfyzyjmjgthb.jpeg?q=90'],
    ['frendo High Speed 1:24 Scale Rechargeable Remote Car Grey', 'Flipkart imported frendo rechargeable remote car listing.', 'Toys', 699, 55, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/remote-control-toy/d/1/d/-original-imahyhhg3akj5guy.jpeg?q=80'],
    ['frendo High Speed 1:24 Scale Rechargeable Remote Car Product View', 'Flipkart imported frendo rechargeable remote car gallery image.', 'Toys', 699, 47, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/remote-control-toy/w/i/v/-original-imahyhhgthznrhas.jpeg?q=80'],
    ['CADDLE & TOES Rock Car Spring Wheels Remote Control Black', 'Flipkart imported CADDLE & TOES rock car remote control toy listing.', 'Toys', 799, 34, 'https://rukminim2.flixcart.com/image/480/640/xif0q/remote-control-toy/m/2/o/rock-car-remote-control-spring-wheels-1-20-scale-wheel-remote-original-imahyh9xwhhksvph.jpeg?q=90'],
    ['DWH 4x4 Remote Control Stunt Car Rechargeable RC Car Black', 'Flipkart imported DWH 4x4 remote control stunt car listing.', 'Toys', 899, 31, 'https://rukminim2.flixcart.com/image/480/640/xif0q/remote-control-toy/9/n/l/4x4-remote-control-stunt-car-for-kids-rechargeable-rc-car-gift-original-imahdxvgpyhy6xmg.jpeg?q=90'],
    ['PLANET Remote Control Fast Modern Racing Car with 3D Light', 'Flipkart imported PLANET remote control racing car listing.', 'Toys', 326, 68, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/remote-control-toy/r/6/m/remote-control-stunt-vehicle-360-rotating-rolling-radio-electric-original-imahhsxfqexkzfky.jpeg?q=80'],
    ['RNAV Rock Crawler Remote Control Car Toys with Mist Smoke', 'Flipkart imported RNAV rock crawler remote control car listing.', 'Toys', 648, 44, 'https://rukminim2.flixcart.com/image/480/640/xif0q/remote-control-toy/x/t/6/rc-drift-car-for-adults-high-speed-4x4-remote-control-car-for-original-imahhfyzjsyz2mzh.jpeg?q=90']
  ],
  'books-store': [
    ['KIPS Information Technology Skill Course Class 10 Subject Code 402 Paperback', 'Flipkart imported KIPS Information Technology Skill Course class 10 paperback listing.', 'Books', 445, 73, 'https://rukminim2.flixcart.com/image/300/300/xif0q/regionalbooks/i/s/x/kips-information-technology-skill-course-10-subject-code-402-original-imags7tfma3wffnz.jpeg?q=90'],
    ['KIPS Information Technology Skill Course Class 10 Book Large View', 'Flipkart imported KIPS class 10 book gallery image.', 'Books', 445, 68, 'https://rukminim2.flixcart.com/image/416/416/xif0q/regionalbooks/i/s/x/kips-information-technology-skill-course-10-subject-code-402-original-imags7tfma3wffnz.jpeg?q=90']
  ],
  'bags-store': [
    ['GEAR Vintage 2 Anti Theft Faux Leather 31 L Laptop Backpack', 'Flipkart imported GEAR Vintage 2 anti-theft faux leather laptop backpack listing.', 'Bags', 1499, 39, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/backpack/i/o/w/-original-imahfskcdqpadznw.jpeg?q=80'],
    ['GEAR Vintage 2 Anti Theft Faux Leather Backpack Side View', 'Flipkart imported GEAR Vintage 2 backpack gallery image.', 'Bags', 1499, 34, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/backpack/l/j/8/-original-imahfskcg24fg3s6.jpeg?q=80'],
    ['GEAR Vintage 2 Anti Theft Faux Leather Backpack Detail View', 'Flipkart imported GEAR Vintage 2 backpack detail image.', 'Bags', 1499, 29, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/backpack/m/3/q/-original-imahfskcpkhytbdh.jpeg?q=80'],
    ['GEAR Vintage 2 Anti Theft Faux Leather Backpack Front View', 'Flipkart imported GEAR Vintage 2 backpack front image.', 'Bags', 1499, 27, 'https://rukminim2.flixcart.com/image/1200/1200/xif0q/backpack/h/r/c/-original-imahfskcafvnsqxg.jpeg?q=80']
  ]
};

const demoProducts = demoStores.flatMap(([, storeSlug]) => (
  importedProductsByStore[storeSlug].map((product) => [...product, storeSlug])
)).map((product, index) => {
  const imageUrl = product[5];
  const separator = imageUrl.includes('?') ? '&' : '?';
  return [
    ...product.slice(0, 5),
    `${imageUrl}${separator}naveeProduct=${index + 1}`,
    product[6]
  ];
});

function slugify(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

module.exports = { demoStores, demoProducts, slugify };
